[project]
name = "weather-data-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "weather",
]

[tool.uv.workspace]
members = [ "libs/weather", "libs/*"]

[tool.uv.sources]
weather = { workspace = true }
